// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV8pzburddGea3TEO6ZFyrmKzzeMPUJME',
    appId: '1:336634436976:web:e4efbe46331cb5d931c3b5',
    messagingSenderId: '336634436976',
    projectId: 'health-care-6b502',
    authDomain: 'health-care-6b502.firebaseapp.com',
    storageBucket: 'health-care-6b502.firebasestorage.app',
    measurementId: 'G-KNMGE7LQKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2377mi9Fra-1YHL6Dit7WZTys_2-6IuA',
    appId: '1:336634436976:android:ade0d0ca86aa6b5431c3b5',
    messagingSenderId: '336634436976',
    projectId: 'health-care-6b502',
    storageBucket: 'health-care-6b502.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArRHLvqQHYZ0-VR2Pxllk5Al-6IPZYzj0',
    appId: '1:336634436976:ios:454022728951d60431c3b5',
    messagingSenderId: '336634436976',
    projectId: 'health-care-6b502',
    storageBucket: 'health-care-6b502.firebasestorage.app',
    iosBundleId: 'com.example.healthCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArRHLvqQHYZ0-VR2Pxllk5Al-6IPZYzj0',
    appId: '1:336634436976:ios:454022728951d60431c3b5',
    messagingSenderId: '336634436976',
    projectId: 'health-care-6b502',
    storageBucket: 'health-care-6b502.firebasestorage.app',
    iosBundleId: 'com.example.healthCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV8pzburddGea3TEO6ZFyrmKzzeMPUJME',
    appId: '1:336634436976:web:129fdc9371f6f07831c3b5',
    messagingSenderId: '336634436976',
    projectId: 'health-care-6b502',
    authDomain: 'health-care-6b502.firebaseapp.com',
    storageBucket: 'health-care-6b502.firebasestorage.app',
    measurementId: 'G-QBJTK55MXP',
  );
}
